name: astrea
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

workspace:
  - package/upload


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: 0.19.0
  get: 4.7.2
  dio: 5.8.0+1
  pretty_dio_logger: 1.4.0
  auto_size_text: 3.0.0
  shared_preferences: 2.5.3
  cached_network_image: 3.4.1
  flutter_screenutil: 5.9.3
  flutter_rating_bar: 4.0.1
  keyboard_visibility_pro: ^1.0.0
  bubble_box: ^0.5.3
  pull_to_refresh: 2.0.0
  flutter_easyloading: 3.0.5
  permission_handler: 12.0.1
  screen_protector: 1.4.2+1
  flutter_slidable: 4.0.0
  wheel_picker: 0.2.2
  #压缩
  flutter_image_compress: 2.4.0
  #国家数据
  intl_country_data: 1.2.9
  bubble_tab_indicator: 0.1.6
  event_bus: ^2.0.1
  logger: 2.6.0
  flutter_svg: ^2.2.0
  url_launcher: 6.3.2
  image_picker: 1.1.2
  path_provider: 2.1.5
  google_sign_in: 6.3.0
  sign_in_with_apple: 7.0.1
  email_validator: 3.0.0
  sprintf: ^7.0.0
  collection: 1.19.1
  lottie: 3.3.1
  #抓包配置
  http_proxy: ^1.2.3
  dio_http2_adapter: ^2.6.0
  #缓存
  dio_cache_interceptor: 4.0.3
  #azlistview_plus: ^3.0.0
  scrollable_positioned_list: 0.3.8
  #logo
  flutter_launcher_icons: ^0.14.4
  #splash
  flutter_native_splash: ^2.4.6
  #判断是否支持google服务
  #google_api_availability: 5.0.1
  webview_flutter: 4.13.0



  awesome_datetime_picker:
    path: plugins/awesome_datetime_picker-master

  custom_navigation_bar:
    path: plugins/custom_bubble_navigation_bar-master



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - launch/
    - assets/
    - assets/svg/
    - assets/json/
    - assets/time/
    - assets/image/
    - assets/background/

  fonts:
    - family: Castoro-Regular
      fonts:
        - asset: fonts/Castoro-Regular.ttf
    - family: SansitaOne
      fonts:
        - asset: fonts/SansitaOne.ttf

#dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path_android: "launch/logo.png"
  #android 13+
  #adaptive_icon_monochrome: "#563E88"
  adaptive_icon_foreground: "launch/logo.png"
  adaptive_icon_background: "#000044"
  min_sdk_android: 26



#dart run flutter_native_splash:create
flutter_native_splash:

  background_image: "launch/splash_bg.png"
  background_image_dark: "launch/splash_bg.png"

  android_12:
    image: launch/logo.png
    color: "#563E88"
    image_dark: launch/logo.png
    color_dark: "#563E88"


  android: true
  ios: false
  web: false