name: astrea
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.8.1

workspace:
  - package/upload

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: 0.20.1
  get: 4.7.2
  dio: 5.8.0+1
  auto_size_text: 3.0.0
  shared_preferences: 2.5.3
  cached_network_image: 3.4.1
  flutter_screenutil: 5.9.3
  keyboard_visibility_pro: 1.0.0
  bubble_box: 0.5.3
  flutter_easyloading: 3.0.5
  permission_handler: 12.0.1
  flutter_slidable: 4.0.0
  wheel_picker: 0.2.2
  flutter_image_compress: 2.4.0
  event_bus: ^2.0.1
  logger: 2.6.0
  flutter_svg: 2.2.0
  url_launcher: 6.3.2
  image_picker: 1.1.2
  path_provider: 2.1.5
  firebase_core: 4.1.0
  firebase_auth: 6.0.2
  google_sign_in: 7.1.1
  sign_in_with_apple: 7.0.1
  email_validator: 3.0.0
  sprintf: 7.0.0
  collection: 1.19.1
  lottie: 3.3.1
  scrollable_positioned_list: 0.3.8
  webview_flutter: 4.13.0
  device_info_plus: 11.5.0
  android_id: 0.4.0
  video_player: 2.10.0
  google_api_availability: 5.0.1
  auto_hyphenating_text: ^0.3.1
  percent_indicator: 4.2.5
  dotted_dashed_line: 0.0.3
  dotted_decoration: 2.0.0
  connectivity_plus: ^6.1.5


  awesome_datetime_picker:
    path: plugins/awesome_datetime_picker-master

  custom_navigation_bar:
    path: plugins/custom_bubble_navigation_bar-master


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/video/
    - assets/json/
    - assets/time/
    - assets/image/
    - assets/data/


  fonts:
    - family: AVENIR-BLACK
      fonts:
        - asset: fonts/AVENIR-BLACK-3.ttf
    - family: Avenir-Medium
      fonts:
        - asset: fonts/Avenir-Medium-6.otf