name: astrea
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

workspace:
  - package/upload


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: 0.19.0
  get: 4.7.2
  dio: 5.8.0+1
  pretty_dio_logger: 1.4.0
  auto_size_text: 3.0.0
  shared_preferences: 2.5.3
  cached_network_image: 3.4.1
  flutter_screenutil: 5.9.3
  flutter_rating_bar: 4.0.1
  keyboard_visibility_pro: ^1.0.0
  bubble_box: ^0.5.3
  pull_to_refresh: 2.0.0
  flutter_easyloading: 3.0.5
  permission_handler: 12.0.1
  screen_protector: 1.4.2+1
  flutter_slidable: 4.0.0
  wheel_picker: ^0.2.2
  #国家数据
  intl_country_data: ^1.2.9
  bubble_tab_indicator: ^0.1.6
  event_bus: ^2.0.1
  logger: ^2.6.0
  flutter_svg: ^2.2.0
  url_launcher: 6.3.2
  image_picker: 1.1.2
  path_provider: 2.1.5
  google_sign_in: 6.3.0
  sign_in_with_apple: 7.0.1
  email_validator: 3.0.0
  sprintf: ^7.0.0
  flutter_native_splash: ^2.4.6
  collection: 1.19.1
  lottie: 3.3.1
  #flutter_image_compress: ^4.0.0



  awesome_datetime_picker:
    path: plugins/awesome_datetime_picker-master

  custom_navigation_bar:
    path: plugins/custom_bubble_navigation_bar-master



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - launch/
    - assets/
    - assets/svg/
    - assets/json/
    - assets/time/
    - assets/image/
    - assets/background/

  fonts:
    - family: Castoro-Regular
      fonts:
        - asset: fonts/Castoro-Regular.ttf
    - family: SansitaOne
      fonts:
        - asset: fonts/SansitaOne.ttf

flutter_native_splash:

  background_image: "launch/splash_bg.png"
  background_image_dark: "launch/splash_bg.png"


  android_12:
    color: "#563E88"
    color_dark: "#563E88"

  android: true
  ios: false
  web: false