import 'package:auto_size_text/auto_size_text.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:astrea/components/bottom_stack_btn.dart';
import 'package:astrea/components/common_app_bar.dart';
import 'package:astrea/core/setting/app_color.dart';
import 'package:astrea/core/setting/app_fonts.dart';
import 'package:astrea/core/translations/en.dart';
import 'package:astrea/generated/assets.dart';
import 'package:astrea/net/api/friend.dart';
import 'package:astrea/page/home/account/select_gender/select_gender.dart';
import 'package:astrea/page/home/synastry/addFile/widget/edit_avatar.dart';
import 'package:astrea/page/home/synastry/addFile/widget/edit_name.dart';
import 'package:astrea/page/home/synastry/addFile/widget/select_birth.dart';

part 'binding.dart';
part 'logic.dart';
part 'view.dart';
